backend/urls.py
from django.urls import path
from backend import views

#TEMPLATE TAGGING
app_name = 'backend'
urlpatterns = [
    path('posts/', views.posts, name='posts'),
    path('posts_by_author/', views.posts_by_author, name='posts_by_author'),
    path('new_post/', views.new_post, name='new_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/', views.update_post, name='update_post'),
    path('edit_post/<int:pk>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:pk>/', views.delete_post, name='delete_post'),
    path('users/', views.users, name='users'),
    path('comments/', views.comments, name='comments'),
    path('moderate_comment/', views.moderate_comment, name='moderate_comment'),
    path('moderate_user/', views.moderate_user, name='moderate_user'),
    path('update/', views.update_profile, name='update_profile'),
    path('tags/', views.tags, name='tags'),
    path('add_new_tag/', views.add_new_tag, name='add_new_tag'),
    path('categories/', views.categories, name='categories'),
    path('add_new_category', views.add_new_category, name="add_new_category"),
    path('settings/', views.settings, name='settings'),
    path('update_settings/', views.update_settings, name='update_settings'),
    path('profile/', views.profile, name='profile'),

]

blog/urls.py
from django.urls import path
from blog import views

#TEMPLATE TAGGING
app_name = 'blog'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('sign-up/', views.registration, name='sign-up'),
    path('<int:year>/', views.archeive_posts, name='archeive_post'),
    path('<int:year>/<int:month>/<int:day>/', views.archeive_posts_by_date, name='archeive_date'),
    path('tag/<str:tag>/', views.archeive_posts_by_tag, name='archeive_tag'),
    path('category/<str:category>/', views.archeive_posts_by_category, name='archeive_category'),
    path('author/<str:username>/', views.archeive_posts_by_author, name='archeive_author'),
    path('posts/<int:pk>/', views.post_details, name='post_details'),
    path('posts/search_result', views.search_view, name='search_view'),
    path('submit_comment', views.submit_comment, name='submit_comment'),
    path('submit_reply', views.submit_reply, name='submit_reply'),

]

blog_engine/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from blog import views
from backend import views


urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', include('blog.urls')),
    path('backend/', include('backend.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models

# Create your models here.

# Blog settings
class BlogSettings(models.Model):
    site_icon = models.ImageField(upload_to='icons')
    site_logo = models.ImageField(upload_to='logos')
    site_title = models.CharField(max_length=200)
    tagline = models.CharField(max_length=200)
    keywords = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    post_per_page = models.IntegerField(default=5)

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from blog.models import Post
from accounts.models import UserProfileInfo

# Create your models here.

# Comment of a post 
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, default=1, related_name='comments')
    content = models.CharField(max_length=1000, blank=True)
    author = models.ForeignKey(UserProfileInfo,on_delete=models.CASCADE,default=1)
    created_date = models.DateTimeField(default=datetime.now())
    published_date = models.DateTimeField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)


    def approve(self):
        self.is_approved = True
        self.save()

    def move_to_trash(self):
        self.delete()

    def get_absolute_url(self):
        return reverse('blog:post_details', args=(post_id, ))

    def __str__(self):
        return self.content


# Reply of a Comment
class Reply(models.Model):
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE, default=10, related_name='replies')
    content = models.CharField(max_length=1000, blank=True)
    author = models.ForeignKey(UserProfileInfo,on_delete=models.CASCADE,default=1)
    published_date = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.title

backend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blog.models import Post,Tag,Category
from accounts.models import UserProfileInfo
from comments.models import Comment,Reply
from .models import BlogSettings
from blog.forms import UserForm,UserProfileInfoForm
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash

# Create your views here.

# verify if an user is an admin
def is_admin(user):
    return user.is_superuser and user.is_staff

# verify if an user is a moderator
def is_moderator(user):
    return user.is_staff

# verify if an user is an author
def is_author(user):
    return user.is_active and not user.is_staff


#@login_required
#Index page with latest posts
def index(request):
    post_list = Post.objects.order_by('published_date')

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    my_dict = {'posts':posts}
    return render(request, 'blog/index.html', context=my_dict)

#list of posts
@user_passes_test(is_moderator)
def posts(request):
    post_list = Post.objects.order_by('published_date')

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    my_dict = {'posts':posts, 'post_page':'post_page'}
    return render(request, 'backend/posts.html', context=my_dict)

#list of posts by author
@user_passes_test(is_author)
def posts_by_author(request):
    post_list = Post.objects.filter(author=request.user).order_by('published_date')

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    my_dict = {'posts':posts, 'post_page_by_author':'post_page_by_author'}
    return render(request, 'backend/posts.html', context=my_dict)

#new post page
@login_required
def new_post(request):
    tags = Tag.objects.all()
    categories = Category.objects.all()


    my_dict = {'new_post':'new_post', 'tags':tags, 'categories':categories }
    return render(request, 'backend/posts.html', context=my_dict)

#process new post
@login_required
def create_post(request):
    if request.method == 'POST' :
        post_title = request.POST.get('post_title')
        post_content = request.POST.get('post_content')
        featured_img = request.FILES.get('featured_img')
        categories = request.POST.getlist('category')
        tags = request.POST.getlist('tag')
        status = request.POST.get('status')
        current_user = request.user
        profile = UserProfileInfo.objects.get(user=current_user)

    post = Post()
    post.title = post_title
    post.content = post_content
    post.featured_img = featured_img
    post.author = User.objects.get(id=current_user.id)

    if status == "Save as Draft":
        post.status = "drafted"

    else:
        post.status = "published"
        post.published_date = datetime.now()


    post.created_date = datetime.now()
    post.updated_date = datetime.now()

    post.save()

    existing_post = Post.objects.get(id=post.id)
    for tag in tags:
        real_tag = Tag.objects.get(text=tag)
        existing_post.tag.add(real_tag)

    for category in categories:
        real_cat = Category.objects.get(text=category)
        existing_post.category.add(real_cat)

    existing_post.save()

    my_dict = {'new_post':'new_post'}
    return render(request, 'backend/posts.html', context=my_dict)


#Post edit page
@login_required
def edit_post(request, pk):
    post = Post.objects.get(id=pk)
    post_tags = post.tag.all()
    other_tags = Tag.objects.all().exclude(tags__pk=pk)
    post_categories = post.category.all()
    other_categories = Category.objects.all().exclude(categories__pk=pk)

    my_dict = {'post':post, 'edit_post':'edit_post', 'post_tags':post_tags, 'post_categories':post_categories,'other_tags':other_tags,'other_categories':other_categories}

    return render(request, 'backend/posts.html', context=my_dict)

#process edit post
@login_required
def update_post(request):
    if request.method == 'POST' :
        post_id = request.POST.get('post_id')
        post_title = request.POST.get('post_title')
        post_content = request.POST.get('post_content')
        featured_img = request.FILES.get('featured_img')

        categories = request.POST.getlist('category')
        tags = request.POST.getlist('tag')


        status = request.POST.get('status')
        current_user = request.user
        profile = UserProfileInfo.objects.get(user=current_user)

    post = Post.objects.get(id=post_id)
    post.title = post_title
    post.content = post_content


    for tag in tags:
        real_tag = Tag.objects.get(text=tag)
        post.tag.add(real_tag)

    for category in categories:
        real_cat = Category.objects.get(text=category)
        post.category.add(real_cat)

    post.featured_img = featured_img
    post.author = User.objects.get(id=current_user.id)

    if status == "Save as Draft":
        post.status = "drafted"
    else:
        post.status = "published"
        post.published_date = datetime.now()

    post.updated_date = datetime.now()

    post.save()

    my_dict = {'new_post':'new_post'}
    return render(request, 'backend/posts.html', context=my_dict)

# process delete post
@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()

    if(request.user.is_staff):
        return HttpResponseRedirect(reverse('backend:posts'))
    else:
        return HttpResponseRedirect(reverse('backend:posts_by_author'))
# list of comments
@user_passes_test(is_moderator)
def comments(request):
    comments = Comment.objects.all();
    my_dict = {'comments':comments}

    return render(request, 'backend/comments.html', context=my_dict)

# approve or delete a comment
@user_passes_test(is_moderator)
def moderate_comment(request):
    if request.method == 'POST':
        comment_id = request.POST.get('comment_id')
        comment = Comment.objects.get(id=comment_id)
        action = request.POST.get('action')

        if action == "approve":
            comment.approve()

        elif action == "trash":
            comment.move_to_trash()

    return HttpResponseRedirect(reverse('backend:comments'))


# modify an user based on action
@user_passes_test(is_admin)
def moderate_user(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user = User.objects.get(id=user_id)
        action = request.POST.get('action')

        if action == "admin":
            user.is_superuser = True
            user.is_staff = True
            user.save()

        elif action == "moderator":
            user.is_superuser = False
            user.is_staff = True
            user.save()


        elif action == "author":
            user.is_superuser = False
            user.is_staff = False
            user.save()

        elif action == "delete":
            user.delete()

    return HttpResponseRedirect(reverse('backend:users'))

# list of users
@user_passes_test(is_admin)
def users(request):
    users = UserProfileInfo.objects.all()
    my_dict = {'users':users}
    return render(request, 'backend/users.html', context=my_dict)

# list of tags
@login_required
def tags(request):
    tags = Tag.objects.all()
    my_dict = {'taxonomy':'Tag','tags':tags }

    return render(request, 'backend/taxonomy.html', context=my_dict)

# list of categories
@login_required
def categories(request):
    categories = Category.objects.all()
    my_dict = {'taxonomy':'category', 'categories':categories}

    return render(request, 'backend/taxonomy.html', context=my_dict)

# process add new tag from taxonomy:tag page
@login_required
def add_new_tag(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        slug = request.POST.get('slug')
    tag = Tag()
    tag.text = text
    tag.slug = slug
    tag.save()

    my_dict = {'taxonomy':'tag'}
    return render(request, 'backend/taxonomy.html', context=my_dict)


# process add new category from taxonomy:category page
@login_required
def add_new_category(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        slug = request.POST.get('slug')
    category = Category()
    category.text = text
    category.slug = slug
    category.save()

    my_dict = {'taxonomy':'category'}
    return render(request, 'backend/taxonomy.html', context=my_dict)

# settings page
@user_passes_test(is_moderator)
def settings(request):

    settings = BlogSettings.objects.get(id=1)
    my_dict = {'settings':settings}
    return render(request, 'backend/settings.html', context=my_dict)


# updating current settings from settings page
@user_passes_test(is_moderator)
def update_settings(request):
    if request.method == "POST":
        icon = request.FILES.get('icon')
        logo = request.FILES.get('logo')
        title = request.POST.get('title')
        tagline = request.POST.get('tagline')
        keywords = request.POST.get('keywords')
        description = request.POST.get('description')
        post_per_page = request.POST.get('post_per_page')



    settings = BlogSettings.objects.get(id=1)

    if icon:
        settings.site_icon = icon
    if logo:
        settings.site_logo = logo

    settings.site_title = title
    settings.tagline = tagline
    settings.keywords = keywords
    settings.description = description
    settings.post_per_page = post_per_page
    settings.save()

    return HttpResponseRedirect(reverse('backend:settings'))

# profile page
@login_required
def profile(request):

comments/views.py
from django.shortcuts import render

# Create your views here.

templates/backend/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="us">
<head>
	<meta charset="utf-8">
  <meta name="description" content="{{description}}">
  <meta name="keywords" content="{{keywords}}">
  <meta name="author" content="xHacker404">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{{site_title}} | {{ tagline }}</title>
	<link rel="icon" href="/media/{{site_icon}}" type="image/gif" sizes="16x16">
	<link href="{% static "css/bootstrap.min.css" %}"rel="stylesheet" type="text/css">
	<link href="{% static "css/jquery-ui.css" %}" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials.css" />
	<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials-theme-classic.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	  <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.css" rel="stylesheet">
	<link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <style type="text/css">
        a.btn{
            color:white;
        }
    </style>
</head>
<body>
    <div class="fluid-container">
    <div class="row">

        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
              <a class="navbar-brand">Dashboard</a>
							<a target="_blank" href="{% url 'index' %}">View Site</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">




                </ul>
                <form class="form-inline my-2 my-lg-0">
                  <img src="/media/{{profile_pic}}" width="50px;" height="50px;" class="profile-icon">
									<h2 style="font-size:24px; padding-left:10px; padding-right:10px"> Hello {{user.username }} </h2>
									<a class="nav-link btn btn-primary" href="{% url 'blog:logout' %}" >Logout</a>
                </form>
              </div>
         </nav>

        </div>


    </div>

        <div class="row" style="margin-top:100px ">
            <div class="col-md-2" id="left-sidebar">

                <div class="list-group">

                    {% if user.is_staff and user.is_superuser %}
										<a href="{% url 'backend:posts'%}" class="list-group-item active">Posts</a>
                    <a href="{% url 'backend:users'%}" class="list-group-item ">Users</a>
                    <a href="{% url 'backend:comments'%}" class="list-group-item ">Comments</a>
                    <a href="{% url 'backend:categories'%}" class="list-group-item ">Categories</a>
                    <a href="{% url 'backend:tags'%}" class="list-group-item ">Tags</a>
										<a href="{% url 'backend:settings'%}" class="list-group-item ">Settings</a>
                    <a href="{% url 'backend:profile'%}" class="list-group-item ">Profile</a>

										{% elif user.is_staff %}
										<a href="{% url 'backend:posts'%}" class="list-group-item active">Posts</a>
										<a href="{% url 'backend:comments'%}" class="list-group-item ">Comments</a>
										<a href="{% url 'backend:categories'%}" class="list-group-item ">Categories</a>
										<a href="{% url 'backend:tags'%}" class="list-group-item ">Tags</a>
										<a href="{% url 'backend:settings'%}" class="list-group-item ">Settings</a>
										<a href="{% url 'backend:profile'%}" class="list-group-item ">Profile</a>

										{% elif user.is_authenticated %}
										<a href="{% url 'backend:posts_by_author'%}" class="list-group-item active">Posts</a>
                    <a href="{% url 'backend:categories'%}" class="list-group-item ">Categories</a>
                    <a href="{% url 'backend:tags'%}" class="list-group-item ">Tags</a>
                    <a href="{% url 'backend:profile'%}" class="list-group-item ">Profile</a>
										{% endif %}


                </div>

            </div>
      	{% block content %}
				{% endblock %}





        </div>

    <div class="row">
            <div class="col-md-12">

                <footer>
                    Copyright &copy; 2018-2019 <a href="#">xHacker404</a>
                </footer>

            </div>

    </div>
    </div>


<script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.js"></script>
<script src="{% static "js/script.js" %}"></script>
<script type="text/javascript">
	// //$("a.list-group-item").addClass('active');
	// $(".btn-dark").on("click", function(e){
	// 	var target = $(e.target);
	// 	$(target).toggleClass('btn');
	//
	// });

	$('#summernote').summernote({
	        placeholder: 'Hello bootstrap 4',
	        tabsize: 2,
	        height: 100
	      });

	function readURL(input) {
			if (input.files && input.files[0]) {
					var reader = new FileReader();

					reader.onload = function (e) {
							$('#profile').attr('src', e.target.result).width(150).height(200);
					};

					reader.readAsDataURL(input.files[0]);
			}
	}




</script>
</body>
</html>

templates/backend/categories.html
<!DOCTYPE html>
{% extends 'backend/base.html'%}
{% block content %}
<div class="col-md-6">


		<div class="post">
					 <div class="form-group">

				<label for="new_tag">Add New Category</label>
				<input type="text" class="form-control" id="new_tag">

				</div>
				<button class="btn btn-primary">Add This Cateogry </button>


		<div class="card" style="margin-top: 44px;">
		</div>
		<div class="card-body">
				<h2 class="card-title" style="font-size:20px;">Available Categories:</h2>
				<ul>
						<li>C</li>
						<li>PHP</li>
						<li>Java</li>
						<li>Python</li>
						<li>JavaScript</li>

				</ul>

		</div>


		</div>



</div>

<div class="col-md-2">



</div>


</div>
{% endblock %}

templates/backend/posts.html
<!DOCTYPE html>
{% extends 'backend/base.html'%}
{% block content %}
{% if post_page %}
<div class="col-md-10" >


		<div class="post" style="height:500px; overflow: scroll">
			<div class="" style="float:right; margin-bottom:10px">
				<a href="{% url 'backend:new_post'%}"class="btn btn-primary"> + New Post </a>
			</div>


				<table class="table">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Post Title</th>
							<th scope="col">Author</th>
							<th scope="col">Date Modified</th>
							<th scope="col">Status</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% if posts %}
							{% for post in posts %}
							<tr>
								<th scope="row">{{ forloop.counter }}</th>
								<td> <a href="/blog/posts/{{post.id}}"> {{ post.title}} </a></td>
								<td><a href="/blog/author/{{post.author}}">{{ post.author}}</a></td>
								<td>{{post.updated_date.year}}/{{post.updated_date.month}}/{{post.updated_date.day}}</td>
								<td>{{post.status}}</td>
								<td>
										<a href="/backend/edit_post/{{post.id}}" class="btn btn-success">edit</a>
										<a href="/backend/delete_post/{{post.id}}" class="btn btn-danger">delete</a>

								</td>
								<td></td>
							</tr>
							{% endfor %}
						{% endif %}
					</tbody>
				</table>
				<div class="pagination">
				<span class="step-links">
						{% if posts.has_previous %}
								<a href="?page=1">&laquo; first</a>
								<a href="?page={{ posts.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
								Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
						</span>

						{% if posts.has_next %}
								<a href="?page={{ posts.next_page_number }}">next</a>
								<a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
						{% endif %}
				</span>
			</div>



		</div>
</div>
{% elif post_page_by_author %}
<div class="col-md-10" >


		<div class="post" style="height:500px; overflow: scroll">
			<div class="" style="float:right; margin-bottom:10px">
				<a href="{% url 'backend:new_post'%}"class="btn btn-primary"> + New Post </a>
			</div>


				<table class="table">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Post Title</th>
							<th scope="col">Date Modified</th>
							<th scope="col">Status</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% if posts %}
							{% for post in posts %}
							<tr>
								<th scope="row">{{ forloop.counter }}</th>
								<td> <a href="/blog/posts/{{post.id}}"> {{ post.title}} </a></td>
								<td>{{post.updated_date.year}}/{{post.updated_date.month}}/{{post.updated_date.day}}</td>
								<td>{{post.status}}</td>
								<td>
										<a href="/backend/edit_post/{{post.id}}" class="btn btn-success">edit</a>
										<a href="/backend/delete_post/{{post.id}}" class="btn btn-danger">delete</a>

								</td>
								<td></td>
							</tr>
							{% endfor %}
						{% endif %}
					</tbody>
				</table>
				<div class="pagination">
				<span class="step-links">
						{% if posts.has_previous %}
								<a href="?page=1">&laquo; first</a>
								<a href="?page={{ posts.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
								Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
						</span>

						{% if posts.has_next %}
								<a href="?page={{ posts.next_page_number }}">next</a>
								<a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
						{% endif %}
				</span>
			</div>



		</div>
</div>
{% elif new_post %}
<div class="col-md-6">


		<div class="post">
				<form action="{% url 'backend:create_post'%}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
				<div class="form-group">

						<label for="post-title">Title:</label>
						<input type="text" id="post-title" class="form-control" name="post_title" value="">

				</div>

				<div class="form-group">
						<label for="summernote">Content:</label>
						<textarea class="form-control" rows="6" id="summernote" name="post_content">

						</textarea>

				</div>

				<div class="form-group" style="float: right">
						<input type="submit" name="status" value="Save as Draft" id="draft" class="btn btn-default">
						<input  type="submit" name="status" id="pubish" class="btn btn-primary" value="Publish">
				</div>


		</div>



</div>

<div class="col-md-2">

		<div class="post-option">

			<h2 style="font-size: 20px">Post Options:</h2>


			<h5>Categories:</h5>
			{% for category in categories %}
			<div class="form-check">
				<input name="category" class="form-check-input" type="checkbox" value="{{category.text}}" id="defaultCheck1">
				<label class="form-check-label" for="defaultCheck1">
					{{category.text}}
				</label>
			</div>
			{% endfor %}
			<h5>Tags:</h5>
			{% for tag in tags %}
			<div class="form-check">
				<input name="tag" class="form-check-input" type="checkbox" value="{{tag.text}}" id="defaultCheck1" >
				<label class="form-check-label" for="defaultCheck1">
					{{tag.text}}
				</label>
			</div>
			{% endfor %}

		<div class="form-group">
				<label for="file" >Select a Featured Image</label>
				<input name="featured_img" type="file" accept="image/*" id="file" class="form-control" onchange="readURL(this);">
				<img id="featured_image" src="" alt="Featured Image">
		</div>

			</form>

		</div>

</div>
{% elif edit_post %}
<div class="col-md-6">


		<div class="post">

				<form action="{% url 'backend:update_post' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}

					<div class="form-group">
							<input type="hidden" name="post_id" value="{{post.id}}" >
							<label for="post-title">Title:</label>
							<input type="text" name="post_title" id="post-title" class="form-control" value="{{post.title}}">

					</div>

					<div class="form-group">
							<label for="content">Content:</label>
							<textarea name="post_content" class="form-control" id="summernote" rows="6">
								{{post.content}}
							</textarea>


					</div>



				<div class="form-group" style="float: right">
					 {% if post.status == 'drafted' %}
					 <input type="submit" name="status" value="Save as Draft" id="draft" class="btn btn-default">
					 <input  type="submit" name="status" id="pubish" class="btn btn-primary" value="Publish">
					 {% else %}
						<button type="submit" id="update" class="btn btn-primary">Update</button>
					 {% endif %}
				</div>

		</div>



</div>

<div class="col-md-2">

		<div class="post-option">

				<h2 style="font-size: 20px">Post Options:</h2>


				<h5>Categories:</h5>
				{% for category in post_categories %}
				<div class="form-check">
					<input name="category" class="form-check-input" type="checkbox" value="{{category.text}}" id="defaultCheck1" checked>
					<label class="form-check-label" for="defaultCheck1">
						{{category.text}}
					</label>
				</div>
				{% endfor %}
				{% for category in other_categories %}
				<div class="form-check">
					<input name="category" class="form-check-input" type="checkbox" value="{{category.text}}" id="defaultCheck1">
					<label class="form-check-label" for="defaultCheck1">
						{{category.text}}
					</label>
				</div>
				{% endfor %}

				<h5>Tags:</h5>
				{% for tag in post_tags %}
				<div class="form-check">
					<input name="tag" class="form-check-input" type="checkbox" value="{{tag.text}}" id="defaultCheck1" checked>
					<label class="form-check-label" for="defaultCheck1">
						{{tag.text}}
					</label>
				</div>
				{% endfor %}
				{% for tag in other_tags %}
				<div class="form-check">
					<input name="tag" class="form-check-input" type="checkbox" value="{{tag.text}}" id="defaultCheck1" >
					<label class="form-check-label" for="defaultCheck1">
						{{tag.text}}
					</label>
				</div>
				{% endfor %}


		</div>

		<div class="form-group">
				<label for="file" >Select a Featured Image</label>
				<input name="featured_img" value="{{post.featured_img}}" type="file" id="file" class="form-control" onchange="readURL(this);">
				<img id="featured_image" src="/media/{{post.featured_img}}" alt="{{post.title}}" width="200px" height="200px">
		</div>

		</div>

</div>
</form>
{% endif %}
{% endblock %}