backend/urls.py
from django.urls import path
from backend import views

#TEMPLATE TAGGING
app_name = 'backend'
urlpatterns = [
    path('posts/', views.posts, name='posts'),
    path('posts_by_author/', views.posts_by_author, name='posts_by_author'),
    path('new_post/', views.new_post, name='new_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/', views.update_post, name='update_post'),
    path('edit_post/<int:pk>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:pk>/', views.delete_post, name='delete_post'),
    path('users/', views.users, name='users'),
    path('comments/', views.comments, name='comments'),
    path('moderate_comment/', views.moderate_comment, name='moderate_comment'),
    path('moderate_user/', views.moderate_user, name='moderate_user'),
    path('update/', views.update_profile, name='update_profile'),
    path('tags/', views.tags, name='tags'),
    path('add_new_tag/', views.add_new_tag, name='add_new_tag'),
    path('categories/', views.categories, name='categories'),
    path('add_new_category', views.add_new_category, name="add_new_category"),
    path('settings/', views.settings, name='settings'),
    path('update_settings/', views.update_settings, name='update_settings'),
    path('profile/', views.profile, name='profile'),

]

blog/urls.py
from django.urls import path
from blog import views

#TEMPLATE TAGGING
app_name = 'blog'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('sign-up/', views.registration, name='sign-up'),
    path('<int:year>/', views.archeive_posts, name='archeive_post'),
    path('<int:year>/<int:month>/<int:day>/', views.archeive_posts_by_date, name='archeive_date'),
    path('tag/<str:tag>/', views.archeive_posts_by_tag, name='archeive_tag'),
    path('category/<str:category>/', views.archeive_posts_by_category, name='archeive_category'),
    path('author/<str:username>/', views.archeive_posts_by_author, name='archeive_author'),
    path('posts/<int:pk>/', views.post_details, name='post_details'),
    path('posts/search_result', views.search_view, name='search_view'),
    path('submit_comment', views.submit_comment, name='submit_comment'),
    path('submit_reply', views.submit_reply, name='submit_reply'),

]

blog_engine/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from blog import views
from backend import views


urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', include('blog.urls')),
    path('backend/', include('backend.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

# Post Taxonomy:Category
class Category(models.Model):
    text = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.text

# Post Taxonomy:Tag
class Tag(models.Model):
    text = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.text

# Blog Post 
class Post(models.Model):
    title = models.CharField(max_length=250,unique=True)
    content = models.CharField(max_length=1000)
    featured_img = models.ImageField(upload_to='featured_images', blank=True)
    tag = models.ManyToManyField(Tag, related_name='tags')
    category = models.ManyToManyField(Category, related_name='categories')
    status = models.CharField(max_length=100, default='drafted')
    author = models.ForeignKey(User,on_delete=models.CASCADE, default=1)
    created_date = models.DateTimeField(default=datetime.now())
    published_date = models.DateTimeField(blank=True, null=True)
    updated_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.status = 'published'
        self.published_date = datetime.now()
        self.updated_date = datetime.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(is_approved = True)

    def get_absolute_url(self):
        return reverse('blog:post_details', args=(post_id, ))

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from accounts.models import UserProfileInfo

#UserForm for Registraiton
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

#UserProfileInfoForm for Registraiton
class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio', 'profile_pic')

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blog.models import Post,Tag,Category
from accounts.models import UserProfileInfo
from comments.models import Comment,Reply
from blog.forms import UserForm,UserProfileInfoForm
from . import forms
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth.models import User


# Create your views here.

#Index page with latest posts
def index(request):
    post_list = Post.objects.filter(status='published').order_by('published_date')

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    my_dict = {'posts':posts}
    return render(request, 'blog/index.html', context=my_dict)

#Post details page
def post_details(request, pk):
    post = Post.objects.get(id=pk)
    post_tags = post.tag.all()
    post_categories = post.category.all()

    next_posts = Post.objects.filter(published_date__gt=post.published_date)
    if(next_posts):
        next_post = next_posts [0]
    else:
        next_post = None

    previous_posts = Post.objects.filter(published_date__lt=post.published_date)
    if(previous_posts):
        previous_post = previous_posts [previous_posts.count()-1]
    else:
        previous_post = None

    post_id = post.id
    comments = post.comments.filter(is_approved=True)



    my_dict = {'post_tags':post_tags,'post_categories':post_categories, 'post':post, 'comments':comments, 'next_post':next_post, 'previous_post':previous_post}
    return render(request, 'blog/single.html', context=my_dict)

#All posts by published year
def archeive_posts(request, year):
    post_list = Post.objects.filter(published_date__year = year)
    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'year':year,'posts':posts}
    return render(request, 'blog/archeive.html', context)

#All posts by post tag
def archeive_posts_by_tag(request, tag):
    tag = Tag.objects.get(text=tag)
    post_list = tag.tags.all()

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'posts':posts}
    return render(request, 'blog/archeive.html', context)

#All posts by post category
def archeive_posts_by_category(request, category):
    category = Category.objects.get(text=category)
    post_list = category.categories.all()
    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'posts':posts}
    return render(request, 'blog/archeive.html', context)

#All posts by a specific author
def archeive_posts_by_author(request, username):
    author = User.objects.get(username=username)
    post_list = Post.objects.filter(author=author.id)

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'posts':posts}
    return render(request, 'blog/archeive.html', context)

#All posts by published_date
def archeive_posts_by_date(request, year, month, day):
    post_list = Post.objects.filter(published_date__year=year, published_date__month=month, published_date__day=day)

    paginator = Paginator(post_list, 5) # Show 5 posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'posts':posts}
    return render(request, 'blog/archeive.html', context)

#Search Result
def search_view(request):
        if request.method == 'GET' :
            search_query = request.GET.get('search_box')
            tag_list = Tag.objects.filter(text__contains=search_query)
            cat_list = Category.objects.filter(text__contains=search_query)
            post_list = Post.objects.filter(title__contains=search_query ).distinct() | Post.objects.filter(content__contains=search_query ).distinct() | Post.objects.filter(tag__id__in=tag_list).distinct() | Post.objects.filter(category__id__in=cat_list).distinct()

        paginator = Paginator(post_list, 5) # Show 5 posts per page
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        context = {'posts':posts}
        return render(request, 'blog/archeive.html', context)

#Comment submission by logged in user
@login_required
def submit_comment(request):

    if request.method == 'POST' :

        comment_title = request.POST.get('comment_title')
        comment_content = request.POST.get('comment_content')
        post_id = request.POST.get('post_id')
        current_user = request.user
        profile = UserProfileInfo.objects.get(user=current_user)

        c = Comment()
        c.post = Post.objects.get(id=post_id)
        c.content = comment_content
        c.author = UserProfileInfo.objects.get(id=profile.id)
        c.published_date = datetime.now()
        c.save()

    return HttpResponseRedirect(reverse('blog:post_details', args=(post_id, )))

#Reply submission by logged in user
@login_required
def submit_reply(request):

    if request.method == 'POST' :
        post_id = request.POST.get('post_id')
        reply_title = request.POST.get('reply_title')
        reply_content = request.POST.get('reply_content')
        comment_id = request.POST.get('comment_id')
        current_user = request.user
        profile = UserProfileInfo.objects.get(user=current_user)

        r = Reply()
        r.comment = Comment.objects.get(id=comment_id)
        r.content = reply_content
        r.author = UserProfileInfo.objects.get(id=profile.id)
        r.published_date = datetime.now()
        r.save()

    return HttpResponseRedirect(reverse('blog:post_details', args=(post_id, ))) # have to work here




#Log out from blog
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

#Authentication and Login
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active and ( user.is_superuser or user.is_staff):
                login(request, user)
                return HttpResponseRedirect(reverse('backend:posts'))
            elif user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User is not active.Please Contact  to Admin")

        else:
            print('Someone tried to login and failed!')
            print('User Name {} and Password {}'.format(username, password))
            return HttpResponse("Invalid login detials provieded")
    else:
        return render(request,'blog/login.html', {})


#New user registration
def registration(request):
    registered = False

    if request.method == 'POST' :
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES :
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'blog/sign-up.html',
                    {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})

templates/blog/archeive.html
<!DOCTYPE html>
{% extends 'blog/base.html'%}
{% block post_block %}
<div class="col-md-7">
	{% if posts %}
			{% for post in posts %}
			<div class="post">
	        <h2><a href="/blog/posts/{{post.id}}"> {{ post.title}} </a></h2>
	        <ul>
	            <li>By  <a href="/blog/author/{{post.author}}">{{ post.author}}</a></li>
	            <li><a href="/blog/{{post.published_date.year}}/{{post.published_date.month}}/{{post.published_date.day}}"> <i class="fa fa-clock-o" aria-hidden="true"></i> {{ post.published_date }}</a></li>

	        </ul>
	        <hr>
					<img src="/media/{{post.featured_img}}" alt="{{post.title}}" width="600px" height="400px" align="center"/></br>
	        <p>{{post.content | safe }}</p>

	        <button class="btn"><a href="/blog/posts/{{post.id}}">Read More</a></button>

	    </div>
		{% endfor %}

		<!-- <nav aria-label="Page navigation example" style="margin-top:22px">
					<ul class="pagination" style="position: relative; align-self: center">

						<li class="page-item"><a class="page-link" href="#">Previous</a></li>
						<li class="page-item"><a class="page-link" href="#">1</a></li>
						<li class="page-item"><a class="page-link" href="#">2</a></li>
						<li class="page-item"><a class="page-link" href="#">3</a></li>
						<li class="page-item"><a class="page-link" href="#">4</a></li>
						<li class="page-item"><a class="page-link" href="#">5</a></li>
						<li class="page-item"><a class="page-link" href="#">6</a></li>
						<li class="page-item"><a class="page-link" href="#">7</a></li>
						<li class="page-item"><a class="page-link" href="#">8</a></li>
						<li class="page-item"><a class="page-link" href="#">9</a></li>
						<li class="page-item"><a class="page-link" href="#">Next</a></li>
					</ul>
		</nav> -->
				<div class="pagination">
				<span class="step-links">
						{% if posts.has_previous %}
								<a href="?page=1">&laquo; first</a>
								<a href="?page={{ posts.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
								Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
						</span>

						{% if posts.has_next %}
								<a href="?page={{ posts.next_page_number }}">next</a>
								<a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
						{% endif %}
				</span>
			</div>
		{% else %}
		<p>Sorry!! No post has been found!!!</p>
		{% endif %}


</div>
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="us">
<head>
	<meta charset="utf-8">
  <meta name="description" content="{{description}}">
  <meta name="keywords" content="{{keywords}}">
  <meta name="author" content="xHacker404">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{{site_title}} | {{ tagline }}</title>
	<link rel="icon" href="/media/{{site_icon}}" type="image/gif" sizes="16x16">
  <link href="{% static "css/bootstrap.min.css" %}"rel="stylesheet" type="text/css">
  <link href="{% static "css/jquery-ui.css" %}" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials.css" />
	<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials-theme-classic.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
  <style type="text/css">

  </style>
</head>
<body>
		<div class="row">

        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
              <a class="navbar-brand" href="{% url 'index'%}">Django Blog</a>
							{% if user.is_staff %}
							<a class="nav-link" href="{% url 'backend:posts' %}" >Dashboard</a>
							{% elif user.is_authenticated %}
							<a class="nav-link" href="{% url 'backend:posts_by_author' %}" >Dashboard</a>
							{% endif %}


              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link " href="#">Contact</a>
                  </li>
                </ul>



                <form class="form-inline my-2 my-lg-0">
									{% if user.is_authenticated %}



									<img src="/media/{{profile_pic}}" width="50px;" height="50px;" class="profile-icon">
									<h2 style="font-size:24px; padding-left:10px; padding-right:10px"> Hello {{user.username }} </h2>
									<a class="nav-link btn btn-outline-primary" href="{% url 'blog:logout' %}" >Logout</a>
									{% else %}
									<a class="nav-link btn btn-outline-primary" href="{% url 'blog:user_login' %}" >Login</a>
                  <a class="nav-link btn btn-outline-success" href="{% url 'blog:sign-up'%}" style="margin-left: 10px">Sign Up</a>
									{% endif %}
								</form>
              </div>
         </nav>

        </div>


    </div>
    <div class="container">
        <div class="row" style="margin-top:100px ">
            <div class="col-md-1" id="left-sidebar"></div>
            {% block post_block %}
            {% endblock %}
            <div class="col-md-4" id="right-sidebar">

								<form class="form-inline" method="GET" action="{% url 'blog:search_view'%}">
									{% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" name="search_box" placeholder="Search">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
               </form>
                 <div class="widget">
                    <h2>Recent Posts</h2>
										{% if all_posts %}
										<ul>
											{% for post in all_posts %}

                        <li> <a href="/blog/posts/{{post.id}}">{{post.title}}</a> </li>

                    	{% endfor %}
										</ul>

										{% else %}
										<p>No Recent Post!</p>
										{% endif %}
                </div>

                <div class="widget">
                    <h2>Archeives</h2>
                    <ul>
											  {% for year in years %}
												<li> <a href="/blog/{{ year }}" />{{ year }}</a> </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget">
                    <h2>Categories</h2>
                    <ul>
											{% for category in categories %}
											<li> <a href="/blog/category/{{ category }}" />{{ category }}</a> </li>
											{% endfor %}


                    </ul>
                </div>

                <div class="widget">
                    <h2>Tags</h2>
                    <ul>
											{% for tag in tags %}
											<li> <a href="/blog/tag/{{ tag }}" />{{ tag }}</a> </li>
											{% endfor %}


                    </ul>
                </div>


            </div>

        </div>




    </div>
    <div class="row">
            <div class="col-md-12">

                <footer>
                    Copyright &copy; 2019 <a href="http://xHacker404.com">xHacker404</a>
                </footer>

            </div>

    </div>

<script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials.min.js"></script>
<script src="{% static "js/script.js" %}"></script>
<script>
        $("#share").jsSocials({
            shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "stumbleupon", "whatsapp"],
						text: "{{ post.title }}",
    				showLabel: true,
    				showCount: false,
        });

				$(".reply-form").hide();

				$(".reply").on("click", function(e){

					var target = $( e.target );
					$(target).siblings(".reply-form").show();
					$(target).hide();

				});



</script>
</body>
</html>

templates/blog/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="us">
<head>
	<meta charset="utf-8">
	<title>{{site_title}}</title>
	<link href="{% static "css/bootstrap.min.css" %}"rel="stylesheet" type="text/css">
	<link href="{% static "css/jquery-ui.css" %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
	<style type="text/css">
	.centered{
	    margin: auto;
	    margin-top:200px;


	}
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
        <div class="col-md-4 centered">

            <form action="{% url 'blog:user_login' %}", method="POST">
								{% csrf_token %}
              <div class="form-group">
                <label for="username">User Name</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Stay Logged in</label>
              </div>
              <button type="submit" class="btn btn-primary">Login</button>
							<br>
							New here?
							<a class="btn btn-outline-success" href="{% url 'blog:sign-up'%}" style="margin-left: 10px">Create an account</a>
            </form>

        </div>


        </div>


    </div>

<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/script.js"></script>
</body>
</html>

templates/blog/single.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block post_block %}
<div class="col-md-7">
    <div class="post">
        {% if post  %}
        <h2>{{post.title}}</h2>
        <ul>
            <li>By <a href="/blog/author/{{post.author}}">{{post.author}}</a></li>
            <li><a href="/blog/posts/{{post.published_date.date}}"> <i class="fa fa-clock-o" aria-hidden="true"></i> {{ post.published_date}}</a></li>

        </ul>
        <hr>
        <img src="/media/{{post.featured_img}}" alt="{{post.title}}" width="600px" height="400px" align="center"/></br>
        <p>
            {{post.content | safe }}
        </p>


       <ul class="pager">

          {% if previous_post %}
          <li style="margin-left:0"><a href="/blog/posts/{{previous_post.id}}">Previous Post</a></li>
          {% endif%}

          {% if next_post %}
          <li style="float: right"><a href="/blog/posts/{{next_post.id}}">Next Post</a></li>
          {% endif %}
        </ul>

        <p><b>Categories:</b>
        {% for category in post_categories %}
        {% if forloop.last %}
        <a href="/blog/category/{{ category.text }}" />{{ category.text }}</a>
        {% else %}
          <a href="/blog/category/{{ category.text }}" />{{ category.text }}</a>,
        {% endif %}
        {% endfor %}
        </p>
        <p><b>Tags:</b>
        {% for tag in post_tags %}
        {% if forloop.last %}
        <a href="/blog/tag/{{ tag.text }}" />{{ tag.text }}</a>
        {% else %}
          <a href="/blog/tag/{{ tag.text }}" />{{ tag.text }}</a>,
        {% endif %}
        {% endfor %}
        </p>



      <div id="share">Share This Post</div>


        <div class="card">

            <div class="card-header">
                    Leave a Comment:
            </div>
            <div class="card-body">

            {% if user.is_authenticated %}
            <form action="{% url 'blog:submit_comment'%}" method="POST">
              {% csrf_token %}

                <div class="form-group">

                  <input type="hidden" name='post_id' value="{{post.id}}">
                    <textarea class="form-control" id="comment-box" rows="3" name="comment_content"></textarea>

                </div>

                <button type="submit" class="btn btn-primary" >Submit</button>

            </form>
            {% else %}
            <form action="#" method="POST">
              {% csrf_token %}

                <div class="form-group">

                  <input type="hidden" name='post_id' value="{{post.id}}">
                    <textarea class="form-control" id="comment-box" rows="3" name="comment_content"></textarea>

                </div>

                <button type="submit" class="btn btn-primary" onclick="login_alert()">Submit</button> <!-- have to work here -->
              </form>

            {% endif %}

            </div>

        </div>

        <div class="row comment">




        {% if comments %}
          {% for comment in comments %}
          <div class="col-md-1 commenter"><img src="/media/{{comment.author.profile_pic}}" alt="50x50"></div>
          <div class="col-md-10 comment-body">
              <h2 style="font-size: 20px">{{comment.author.user}}</h2>
              <p>{{comment.content}}</p>
              {% if comment.replies.all %}
                {% for reply in comment.replies.all %}
                <div class="row rpl" style="margin-top:22px">

                    <div class="col-md-1 commenter">
                        <img src="/media/{{reply.author.profile_pic}}" alt="50x50" >
                    </div>

                    <div class="col-md-9 comment-body">
                        <h2 style="font-size:20px">{{reply.author.user}}</h2>
                        <p>{{ reply.content}} </p>
                        {% if forloop.last %}
                        {% if user.is_authenticated %}
                        <form action="{% url 'blog:submit_reply'%}" method="POST">
                          {% csrf_token %}

                            <div class="form-group">

                              <input type="hidden" name='post_id' value="{{comment.post.id}}">
                              <input type="hidden" name='comment_id' value="{{comment.id}}">
                                <textarea class="form-control" id="comment-box" rows="3" name="reply_content"></textarea>

                            </div>
                            <button type="submit" class="btn btn-primary">Reply</button>
                          </form>
                          {% else %}
                          <form action="#" method="POST">
                            {% csrf_token %}

                              <div class="form-group">

                                <textarea class="form-control" id="comment-box" rows="3" name="reply_content"></textarea>

                              </div>
                              <button type="submit" class="btn btn-primary" onclick="login_alert()">Reply</button>
                            </form>

                          {% endif %}

                        {% endif %}
                    </div>


                </div>
                {% endfor %}


              {% else %}
                <button type="button" class="btn reply">Reply</button>
                {% if user.is_authenticated %}
                <form class="reply-form" action="{% url 'blog:submit_reply'%}" method="POST">
                  {% csrf_token %}

                    <div class="form-group">


                      <input type="hidden" name='post_id' value="{{comment.post.id}}">
                      <input type="hidden" name='comment_id' value="{{comment.id}}">
                        <textarea class="form-control" id="comment-box" rows="3" name="reply_content"></textarea>

                    </div>

                    <button type="submit" class="btn btn-primary">Reply</button>
                    {% else %} <!-- have to work here -->
                    <form class="reply-form" action="#" method="POST">
                      {% csrf_token %}

                        <div class="form-group">


                          <input type="hidden" name='post_id' value="{{comment.post.id}}">
                          <input type="hidden" name='comment_id' value="{{comment.id}}">
                            <textarea class="form-control" id="comment-box" rows="3" name="reply_content"></textarea>

                        </div>

                    <button type="submit" class="btn btn-primary" onclick="login_alert()">Reply</button>
                    {% endif %}
                  </form>
              {% endif %}



          </div>

          {% endfor %}
      
        {% endif %}


      </div>
    </div>
    {% else %}
    <p>Post Has been deleted OR 404!!!!</p>
    {% endif %}




</div>
{% endblock %}